
name: Just run makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      run : sudo apt-get install build-essential gawk gcc g++ gfortran git texinfo bison libncurses-dev
    - name: setup toolchain
      run: wget https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%208.3.0/Raspberry%20Pi%202%2C%203/cross-gcc-8.3.0-pi_2-3.tar.gz/download
    - run: tar xf download
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make
      run: |
        export LD_LIBRARY_PATH=/home/runner/work/cellar-driver/cellar-driver/cross-pi-gcc-8.3.0-1/lib:$LD_LIBRARY_PATH
        export PATH=/home/runner/work/cellar-driver/cellar-driver/cross-pi-gcc-8.3.0-1/bin:$PATH;
        echo "-------"
        echo $PATH;
        echo "-------"
        echo $LD_LIBRARY_PATH;
        echo "-------"
        ls /home/runner/work/
        echo "-------"


        cd src/main/c;
        ./compile_arm.sh

