
name: Just run makefile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make
      run: |
        sudo apt-get install build-essential gawk gcc g++ gfortran git texinfo bison libncurses-dev;
        wget -nv https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%208.3.0/Raspberry%20Pi%202%2C%203/cross-gcc-8.3.0-pi_2-3.tar.gz/download;
        tar xf download;
        export LD_LIBRARY_PATH=/home/runner/work/cellar-driver/cellar-driver/cross-pi-gcc-8.3.0-1/lib:$LD_LIBRARY_PATH
        export PATH=/home/runner/work/cellar-driver/cellar-driver/cross-pi-gcc-8.3.0-1/bin:$PATH;
        cd src/main/c;
        ./compile_arm.sh
    - name: package
      run: mkdir staging && cp src/main/c/testAdafruit staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
