# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: tools versions
      run: gcc -v
    - name: setup toolchain
      run: wget https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%208.3.0/Raspberry%20Pi%202%2C%203/cross-gcc-8.3.0-pi_2-3.tar.gz/download
    - name: untar toolchain
      run: tar xf download
    - name: setup linking
      run: export PATH=cross-pi-gcc-8.3.0-1/bin:$PATH; export LD_LIBRARY_PATH=/cross-pi-gcc-8.3.0-1/lib:$LD_LIBRARY_PATH
    - name: install deps
      run : sudo apt-get install build-essential gawk gcc g++ gfortran git texinfo bison libncurses-dev
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
